### ISSUE TITLE
Issues with the products.model.ts in /src

### ISSUE THREAD

**Issue by kuang66** [worldsibu/convector-cli#33]
Hi, I am really new to hyperledger and was trying out convector, but bumped into some errors while I was running _npm i_

_conv new 2ndproject -c products
cd 2ndproject
npm i_

Here's the screenshot of the error 
![image](https://user-images.githubusercontent.com/48782555/54734429-8579d100-4bf3-11e9-8524-0d259d2e55f0.png)

So I opened up the products.model.ts and found the _extends extends_ keyword
![image](https://user-images.githubusercontent.com/48782555/54734454-b8bc6000-4bf3-11e9-9d87-16fd1ef1f0ba.png)

After removing the extra extends, npm i completed without any errors
![image](https://user-images.githubusercontent.com/48782555/54734537-4f891c80-4bf4-11e9-8ddf-f02734914242.png)

Hopefully, this could be useful. Do let me know if I am not supposed to remove the 2nd extends. Happy and keen to contribute to this project if you guys need some help

**Comment by b3of** [comment]
I think there’s already a PR for this issue. https://github.com/worldsibu/convector-cli/pull/32

**Comment by walmon** [comment]
We checked the code and in the history of that file there has never been two extend words. Did that happen twice? I mean if you run it again you get the same issue
I tried to replicate it without success
