### ISSUE TITLE
Cannot create new project

### ISSUE THREAD

**Issue by abhijits3** [worldsibu/convector-cli#37]
running conv new attributesDb -c person show the following prompt
? May Convector CLI anonymoysly report usage statistics to improve the tool over time? (Y/n)
Nothing happens after this. The folder for the new project is not created.

**Comment by abhijits3** [comment]
OS: Ubuntu 18.04.2
NPM: 6.4.1
Node:  10.15.3
convector-cli: 1.1.3

This is happening everytime. I am not able to create a new project

**Comment by walmon** [comment]
Looks like you are using an unsupported version of NodeJS. Please refer to the following link https://github.com/worldsibu/convector-cli#prerequisites

You may use NVM to install the required version next to your current version https://github.com/creationix/nvm

Feel free to comment again if you face the same issue with the right version of Node installed.

**Comment by abhijits3** [comment]
sure Thanks for the prompt reply..will try and let you know.

**Comment by abhijits3** [comment]
this worked with node version 8.11.4 Although I had to use sudo for conv new attributesDb -c person.
Thanks
