### ISSUE TITLE
*.participant.config.json files are not created

### ISSUE THREAD

**Issue by gnom1gnom** [worldsibu/convector-cli#44]
OS: Ubuntu 18.04.3 LTS
Node: v8.11.0
npm: 5.6.0
conv: 1.1.7

In your tutorials _conv new_ generates
- org1.xxx.config.json
- org2.xxx.config.json

On my setup this files are not created, yet now error is raised.
Is this by design in the latest version or is it an error in my setup?

**Comment by diestrin** [comment]
Those `org#.xxx.config.json` files were consolidated in a single `xxx.config.json` file.
