### ISSUE TITLE
Feed back the user of what is happening 

### ISSUE THREAD

**Issue by walmon** [worldsibu/convector-cli#5]
When executing a command, tell the user what is going on.

Follow Angular-CLI example for instance.

<img width="730" alt="screen shot 2018-11-11 at 1 28 56 pm" src="https://user-images.githubusercontent.com/5282988/48317336-ec3c0d80-e5b5-11e8-905e-93adc8274b73.png">

**Comment by josuegb** [comment]
Solved: https://github.com/worldsibu/convector-cli/pull/15
